### ISSUE TITLE
fstrim deactivated?

### ISSUE THREAD

**Issue by Krawei** [LineageOS/android_device_bq_bardockpro#2]
Dear LineageOS-Team, dear @brinlyau , @cmorlok , @eloimuns @kra1o5 , 

due to a post in the german android-hilfe forum[1] I'm wondering if your ROM's kernel is related to the "official BQ" one.

The reason is, a third-party-commit seems to disable fstrim for the /date partition since their firmware-release 2.3.0. You can find the related commit under [2]. 

I hope you can shed some light in the dark here :).

Kind regards,

Krawei.

[1]: https://www.android-hilfe.de/forum/bq-aquaris-x-x-pro.3053/fstrim-lebenszeit-des-internen-speichers.914583.html
[2]: https://github.com/bq/aquaris-X-Pro/commit/93dae1af05a8148315c850766ddf487428858e4c#diff-d6173cb103a1764f735c908edf5f3e5d

**Comment by Krawei** [comment]
Any updates Herr?

**Comment by stucki** [comment]
Thanks for reporting, this is being processed currently: https://review.lineageos.org/c/LineageOS/android_kernel_bq_msm8953/+/250516

**Comment by Krawei** [comment]
Hello @stucki : Thank for your reply and the link to your gerrit post. Is this Github-Page the right place to open tickets or should I use another source? 
I've some another findings in LOS 16 and would like to share them with you.

**Comment by stucki** [comment]
@Krawei It's ok to report them here. However, I didn't notice it because notification for the repository was turned off for me. If you don't get feedback, please ping me!

**Comment by stucki** [comment]
@Quallenauge Please close this ticket. Thanks!

**Comment by Quallenauge** [comment]
@Krawei It's more common to add the issues here: https://gitlab.com/LineageOS/issues/android
See https://wiki.lineageos.org/bugreport-howto.html for details.
Reason: I only have permissions for pushing commits, but not for issues and so on. Therefore I can't close it :-(
